OrdererOrgs:
  - Name: Orderer
    Domain: bot.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.bot.com
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: Org2
    Domain: org2.bot.com
    Template:
      Count: 2
    Users:
      Count: 2
